### ISSUE TITLE
Documentation: TypeError: Robinhood is not a function

### ISSUE THREAD

**Issue by patrocinio** [aurbano/robinhood-node#45]
// Below is an issue template, feel free to modify it

Code being executed:

```js
var Robinhood = require('robinhood')(credentials, function(){

    //Robinhood is connected and you may begin sending commands to the api.

    Robinhood(null).quote_data('GOOG', function(error, response, body) {
        if (error) {
            console.error(error);
            process.exit(1);
        }
        console.log(body);
    });

});
```

### Expected result

See GOOG's quote
// A little explanation, sample response JSON...

### Actual behaviour

// Either the error you received, or the JSON that was returned
Eduardos-MBP:robinhood edu$ node robinhood.js
/Users/edu/github/robinhood/robinhood.js:12
    Robinhood(null).quote_data('GOOG', function(error, response, body) {
    ^

TypeError: Robinhood is not a function
    at /Users/edu/github/robinhood/robinhood.js:12:5
    at /Users/edu/node_modules/robinhood/src/robinhood.js:86:18
    at Request._callback (/Users/edu/node_modules/robinhood/src/robinhood.js:126:18)
    at Request.self.callback (/Users/edu/node_modules/robinhood/node_modules/request/request.js:186:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Users/edu/node_modules/robinhood/node_modules/request/request.js:1081:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/Users/edu/node_modules/robinhood/node_modules/request/request.js:1001:12)
### Reproducing

// Please provide a bit of context for the code snippet, were you authenticated?
The line

Robinhood(null).quote_data('GOOG', function(error, response, body) {

should be 

Robinhood.quote_data('GOOG', function(error, response, body) {

**Comment by aurbano** [comment]
Thanks for your fix for this!
